Excel/01 Using Microsoft Graph APIs with Excel/Completed Solutions/Exercise 4/GraphExcel - Copy/GraphExcel/Models/AdalTokenCache.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Security;
using Microsoft.IdentityModel.Clients.ActiveDirectory;

namespace GraphExcel.Models
{
    public class ADALTokenCache : TokenCache
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private string userId;
        private UserTokenCache Cache;

        public ADALTokenCache(string signedInUserId)
        {
            // associate the cache to the current user of the web app
            userId = signedInUserId;
            this.AfterAccess = AfterAccessNotification;
            this.BeforeAccess = BeforeAccessNotification;
            this.BeforeWrite = BeforeWriteNotification;
            // look up the entry in the database
            Cache = db.UserTokenCacheList.FirstOrDefault(c => c.webUserUniqueId == userId);
            // place the entry in memory
            this.Deserialize((Cache == null) ? null : MachineKey.Unprotect(Cache.cacheBits,"ADALCache"));
        }

        // clean up the database
        public override void Clear()
        {
            base.Clear();
            var cacheEntry = db.UserTokenCacheList.FirstOrDefault(c => c.webUserUniqueId == userId);
            db.UserTokenCacheList.Remove(cacheEntry);
            db.SaveChanges();
        }

        // Notification raised before ADAL accesses the cache.
        // This is your chance to update the in-memory copy from the DB, if the in-memory version is stale
        void BeforeAccessNotification(TokenCacheNotificationArgs args)
        {
            if (Cache == null)
            {
                // first time access
                Cache = db.UserTokenCacheList.FirstOrDefault(c => c.webUserUniqueId == userId);
            }
            else
            { 
                // retrieve last write from the DB
                var status = from e in db.UserTokenCacheList
                             where (e.webUserUniqueId == userId)
                select new
                {
                    LastWrite = e.LastWrite
                };

                // if the in-memory copy is older than the persistent copy
                if (status.First().LastWrite > Cache.LastWrite)
                {
                    // read from from storage, update in-memory copy
                    Cache = db.UserTokenCacheList.FirstOrDefault(c => c.webUserUniqueId == userId);
                }
            }
            this.Deserialize((Cache == null) ? null : MachineKey.Unprotect(Cache.cacheBits, "ADALCache"));
        }

        // Notification raised after ADAL accessed the cache.
        // If the HasStateChanged flag is set, ADAL changed the content of the cache
        void AfterAccessNotification(TokenCacheNotificationArgs args)
        {
            // if state changed
            if (this.HasStateChanged)
            {
                Cache = new UserTokenCache
                {
                    webUserUniqueId = userId,
                    cacheBits = MachineKey.Protect(this.Serialize(), "ADALCache"),
                    LastWrite = DateTime.Now
                };
                // update the DB and the lastwrite 
                db.Entry(Cache).State = Cache.UserTokenCacheId == 0 ? EntityState.Added : EntityState.Modified;
                db.SaveChanges();
                this.HasStateChanged = false;
            }
        }

        void BeforeWriteNotification(TokenCacheNotificationArgs args)
        {
            // if you want to ensure that no concurrent write take place, use this notification to place a lock on the entry
        }

        public override void DeleteItem(TokenCacheItem item)
        {
            base.DeleteItem(item);
        }
    }
}

Excel/01 Using Microsoft Graph APIs with Excel/Completed Solutions/Exercise 4/GraphExcel - Copy/GraphExcel/Models/ToDoItem.cs
using System;
using Newtonsoft.Json.Serialization;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace GraphExcel.Models
{
    public class ToDoItem
    {
        [JsonProperty("index")]
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Status { get; set; }
        [Required]
        public string Priority { get; set; }
        [Required]
        public string PercentComplete { get; set; }
        [Required]
        public string StartDate { get; set; }
        [Required]
        public string EndDate { get; set; }
        [DataType(DataType.MultilineText)]
        public string Notes { get; set; }
        public ToDoItem(
            int id,
            string title,
            string priority,
            string status,
            string percentComplete,
            string startDate,
            string endDate,
            string notes)
        {
            Id = Convert.ToInt32(id);
            Title = title;
            Priority = priority;
            Status = status;
            if (!percentComplete.EndsWith("%"))
                PercentComplete = percentComplete + "%";
            else
                PercentComplete = percentComplete;

            StartDate = startDate;
            EndDate = endDate;
            Notes = notes;
        }
        public ToDoItem() { }
    }
}

Excel/01 Using Microsoft Graph APIs with Excel/Completed Solutions/Exercise 4/GraphExcel - Copy/GraphExcel/Controllers/ChartController.cs
using System.Web.Mvc;
using System.Threading.Tasks;
using GraphExcel.Helpers;

namespace GraphExcel.Controllers
{
    public class ChartController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }
        public async Task<FileResult> GetChart()
        {
            ExcelAPIHelper _restAPIHelper = new ExcelAPIHelper();
            return await _restAPIHelper.getChartImage();
        }
    }
}

Excel/01 Using Microsoft Graph APIs with Excel/Completed Solutions/Exercise 4/GraphExcel - Copy/GraphExcel/Controllers/ToDoListController.cs
using System.Web.Mvc;
using System.Threading.Tasks;
using GraphExcel.Helpers;

namespace GraphExcel.Controllers
{
    public class ToDoListController : Controller
    {
        ExcelAPIHelper _restAPIHelper = new ExcelAPIHelper();

        [Authorize]
        public async Task<ActionResult> Index()
        {
            return View(await _restAPIHelper.GetToDoItems());
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            var priorityList = new SelectList(new[]
                                          {
                                          new {ID="1",Name="High"},
                                          new{ID="2",Name="Normal"},
                                          new{ID="3",Name="Low"},
                                      },
                            "ID", "Name", 1);
            ViewData["priorityList"] = priorityList;

            var statusList = new SelectList(new[]
                              {
                                          new {ID="1",Name="Not started"},
                                          new{ID="2",Name="In-progress"},
                                          new{ID="3",Name="Completed"},
                                      },
                "ID", "Name", 1);
            ViewData["statusList"] = statusList;

            return View();
        }
        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Create(FormCollection collection)
        {
            try
            {

                await _restAPIHelper.CreateToDoItem(
                    collection["Title"],
                    collection["PriorityDD"],
                    collection["StatusDD"],
                    collection["PercentComplete"],
                    collection["StartDate"],
                    collection["EndDate"],
                    collection["Notes"]);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Excel/01 Using Microsoft Graph APIs with Excel/Completed Solutions/Exercise 4/GraphExcel - Copy/GraphExcel/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Percent Complete Chart</h2>
<img src="@Url.Action("GetChart", "Chart")" />

<div>
    @Html.ActionLink("Back to To Do List", "Index", "ToDoList")
</div>

Excel/01 Using Microsoft Graph APIs with Excel/Completed Solutions/Exercise 4/GraphExcel - Copy/GraphExcel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("To Do List", "Index", "ToDoList")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>